# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1b2e14113371f7c11bcc8436c4aa6cc240c4ef22f058972ffbbed69f1dac3525cdb41e6abda46443815aebf54e4cba342dca95d1b4289d65ffd01a13ed807c95

test:
  secret_key_base: 6e01dc4d7bc39df6c354be4a5c6e31fdfe4987239dda25b30af5872fcfe8338d6b2ac4ba38f79b55b62f0cdc51fce807c8e9a0c3a0d075514522032eee4de502

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
